### ISSUE TITLE
Time consuming to save a big temp file in each session of the loop.

### ISSUE THREAD

**Issue by MinhChauNGUYEN** [alexis-michaud/egg#3]
In each session of the loop, it take a long time to save whole data before continuing run the next token.

**Comment by alexis-michaud** [comment]
Yes, well spotted 👍 : as a safeguard against losing data in the middle of a long session (for instance in the event of power failure), `peakdet` does a backup at the end of the loop.*

*"Each session of the loop" is not a good way to express this: I think it would be more correct to say "at each iteration of the loop" or "at the end of the loop body", and to reserve "session" to refer to the user's "session": from the moment the user starts `peakdet` to the moment the final results are saved by the user.

It takes time because the temporary save contains the *whole* workspace, including the electroglottographic signal, its derivative, etc. If the signal is a big file (as a rule of thumb: more than 5 minutes), then this takes time. Currently I use SSD (Solid State Drive) storage, which is remarkably fast (faster than SATA hard drives), and the WAV files I deal with are less than 10 minutes long, so I did not notice the issue, even for big files. 

It's fixed, through commit 6f006e6aa80853c50bb7c605df9e6909f97d9a71

Here is the new code: 

```
    % saving the results in a temporary data file: this can be recovered in
    % case MatLab suddenly closes (due to computer crash, power supply
    % problem...).
    % This line of code only saves the data matrix, so as to avoid writing
    % a huge file containing the EGG signal, its derivative etc. at each
    % iteration of the loop processing 1 item. A drawback is that
    % <tempdata> does not contain the whole work space: to resume the work
    % where the user left off, it is necessary to re-load the EGG file,
    % etc. If file size is not an issue, comment this line of code and
    % uncomment the line below, which saves the whole workspace.
    save peakdet_tempdata data
%    save peakdet_tempdata
```
